name: hsm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy<2
  - matplotlib
  - pyyaml
  - pyrender
  - natsort
  - omegaconf

  # For GPT
  - openai
  - python-dotenv

  # For Trimesh
  - trimesh=4
  - scipy
  - pillow
  - rtree
  - shapely
  
  # For CLIP
  - pytorch
  - torchvision
  # - pytorch-cuda=12.1
  - regex
  - tqdm
  - open-clip-torch

  - pip:
    - huggingface-hub

    # For trimesh collision detection and raycasting
    - python-fcl
    - manifold3d
    # - embreex  # Uncomment for faster trimesh raycasting on x86_64 platforms

    - earcut
    - compress_json